language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "6.10"
  - "8.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - export CXX="g++-4.8"
sudo: false
